# アプリケーション基本設定
spring.application.name=ses-app

# データベース接続設定（DockerのPostgreSQL、ポート5433へ繋ぐ）
spring.datasource.url=jdbc:postgresql://localhost:5433/ses_db
spring.datasource.username=ses_user
spring.datasource.password=ses_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernateの設定（JavaとSQLの自動連携設定）
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true